//
// Created by konek on 7/14/2019.
//

#ifndef MEDIA_PLAYER_PRO_VST_H
#define MEDIA_PLAYER_PRO_VST_H

typedef int VST_TYPEDEF_RETURN_TYPE;

VST_TYPEDEF_RETURN_TYPE VST_STATE = 0;

#define VST_FUNCTION_CREATE VST_TYPEDEF_RETURN_TYPE GraphicsCreate()
#define VST_FUNCTION_RESIZE VST_TYPEDEF_RETURN_TYPE GraphicsResize(int width, int height)
#define VST_FUNCTION_DRAW VST_TYPEDEF_RETURN_TYPE GraphicsDraw()
#define VST_FUNCTION_DESTROY VST_TYPEDEF_RETURN_TYPE GraphicsDestroy()
#define VST_RETURN_CONTINUE 0
#define VST_RETURN_RESTART 2
#define VST_RETURN_STOP 1
#ifndef CALLBACKNATIVE
#define CALLBACKNATIVE extern "C"
#endif

int VST_API_IMPLEMENTATION_WINDOWS = 0;
int VST_API_IMPLEMENTATION_LINUX = 1;
extern int VST_API_IMPLEMENTATION;

#endif //MEDIA_PLAYER_PRO_VST_H
